### ISSUE TITLE
The Config example link is not working on Bitrise Integration page

### ISSUE THREAD

**Issue by moatazeldebsy** [odemolliens/bitrise-step-monitoring-apps-sizes#4]
Hi, I was checking the step on the Bitrise integrations page, and when I click on the config example in the desc. it's redirected to the Bitrise home page because in the README file it's using` #config-file-example` , can we fix it? Thanks

<img width="733" alt="Screenshot 2021-04-13 at 09 13 33" src="https://user-images.githubusercontent.com/45570191/114511743-98c3c300-9c38-11eb-97a4-25973d3226d9.png">

**Comment by imranMnts** [comment]
👋🏼  

Issue fixed in v1.0.2
